//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4StudentsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseTable
    {
        public CourseTable()
        {
            this.EnrolmentTables = new HashSet<EnrolmentTable>();
        }
    
        public int CourseID { get; set; }
        public string CourseTitle { get; set; }
        public string CourseRoom { get; set; }
        public Nullable<System.DateTime> CourseDate { get; set; }
        public string CourseDuration { get; set; }
    
        public virtual ICollection<EnrolmentTable> EnrolmentTables { get; set; }
    }
}
