//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4StudentsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnrolmentTable
    {
        public int EnrolmentID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual CourseTable CourseTable { get; set; }
        public virtual StudentTable StudentTable { get; set; }
    }
}
