//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC4StudentsApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public StudentTable()
        {
            this.EnrolmentTables = new HashSet<EnrolmentTable>();
        }
    
        public int StudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentAddress { get; set; }
        public string StudentPhone { get; set; }
        public string StudentEmail { get; set; }
    
        public virtual ICollection<EnrolmentTable> EnrolmentTables { get; set; }
    }
}
